### ISSUE TITLE
Installer not working on darwin

### ISSUE THREAD

**Issue by daniel-farina** [Zondax/ledger-namada#21]
Hi guys, 

The installer is not working on Mac. I'm getting:

```
(base) ➜  Desktop ./install.sh load
Generated random root public key : b'049ca3e107f1eecaca95a10dd321aff7b470b815482558d48b11e32f420db064ecd39e6061ab2be8f799cdb87054c58c200bb8e2a992d998e6344e0e089035d462'
Traceback (most recent call last):
  File "/Users/web/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/web/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/web/anaconda3/lib/python3.10/site-packages/ledgerblue/loadApp.py", line 175, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/Users/web/anaconda3/lib/python3.10/site-packages/ledgerblue/deployed.py", line 88, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/Users/web/anaconda3/lib/python3.10/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 5515 (Unknown reason)
```

**Comment by ftheirs** [comment]
Hi @daniel-farina, I'm using mac too and the installer script is working fine. If you check the output, you're getting some errors. That might be caused by an old version from ledgerblue, the usb port might be used by another app, etc. 

If you want an easier way to install the app, you can check [ZondaxHub](https://hub.zondax.ch/namada) but keep in mind that this is not the final version and the official release from Ledger is not published yet. It is intended for testing purposes
