### ISSUE TITLE
Cannot load the ledger App on a Nano S plus

### ISSUE THREAD

**Issue by phy-chain** [Zondax/ledger-namada#30]
I have downloaded the script, installed pip, and ran the `./installer.sh load command`, it seems to be generating the keys but then breaks with the following error :

```
Generated random root public key : b'xxx'
Using test master key b'xxx' 
Using ephemeral key b'xxx'
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ledgerblue/loadApp.py", line 253, in <module>
    loader.createApp(code_length, args.apiLevel, args.dataSize, paramsSize, args.appFlags, args.bootAddr|1)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ledgerblue/hexLoader.py", line 374, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ledgerblue/hexLoader.py", line 207, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6512 (Unknown reason)

```

Any idea how this could be fixed ?

Python version : 3.10.0
Pip version : 22.0.2
Ledgerblue : 0.1.48

**Comment by carlosala** [comment]
Hi! Make sure you are in the latest firmware version `v1.1.1`. You can update in Ledger Live app.

**Comment by phy-chain** [comment]
Fair enough, Im not up to date I thiink. This ledger has been sleeping in its packaging for like 12 months.
Updating...

**Comment by phy-chain** [comment]
Yep, I can confirm. I updated to 1.1.1 and everything worked. 
Installation ok. Lets have some fun !
Thanks for the pointer
